const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  LevelFormat, PageBreak
} = require('docx');
const fs = require('fs');

const CW = 9360;
const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const B = { top: border, bottom: border, left: border, right: border };
const hb = { style: BorderStyle.SINGLE, size: 1, color: "1A3A5C" };
const HB = { top: hb, bottom: hb, left: hb, right: hb };

function h1(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 200 },
    children: [new TextRun({ text, bold: true, size: 32, color: "1A3A5C", font: "Arial" })] });
}
function h2(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 160 },
    children: [new TextRun({ text, bold: true, size: 26, color: "1A3A5C", font: "Arial" })] });
}
function h3(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 220, after: 120 },
    children: [new TextRun({ text, bold: true, size: 22, color: "2E6DA4", font: "Arial" })] });
}
function tag(text, color = "C0392B") {
  return new Paragraph({ spacing: { before: 160, after: 80 },
    children: [new TextRun({ text, bold: true, size: 20, color, font: "Arial" })] });
}
function para(text, italic = false) {
  return new Paragraph({ spacing: { before: 80, after: 80 },
    children: [new TextRun({ text, size: 22, font: "Arial", italics: italic })] });
}
function bul(text, lvl = 0) {
  return new Paragraph({ numbering: { reference: "bullets", level: lvl }, spacing: { before: 60, after: 60 },
    children: [new TextRun({ text, size: 22, font: "Arial" })] });
}
function num(text, lvl = 0) {
  return new Paragraph({ numbering: { reference: "numbers", level: lvl }, spacing: { before: 60, after: 60 },
    children: [new TextRun({ text, size: 22, font: "Arial" })] });
}
function code(text) {
  return new Paragraph({ spacing: { before: 40, after: 40 }, indent: { left: 360 },
    children: [new TextRun({ text, size: 18, font: "Courier New", color: "1A1A1A" })] });
}
function codes(lines) { return lines.map(l => code(l)); }
function sep() {
  return new Paragraph({ spacing: { before: 180, after: 180 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" } }, children: [] });
}
function pb() { return new Paragraph({ children: [new PageBreak()] }); }
function note(text, fill = "FFF3CD") {
  return new Table({ width: { size: CW, type: WidthType.DXA }, columnWidths: [CW],
    rows: [new TableRow({ children: [new TableCell({ borders: B, width: { size: CW, type: WidthType.DXA },
      shading: { fill, type: ShadingType.CLEAR }, margins: { top: 100, bottom: 100, left: 160, right: 160 },
      children: [new Paragraph({ children: [new TextRun({ text, size: 20, font: "Arial", italics: true })] })] })] })] });
}
function tblH(cells, ws) {
  return new TableRow({ tableHeader: true, children: cells.map((t, i) =>
    new TableCell({ borders: HB, width: { size: ws[i], type: WidthType.DXA },
      shading: { fill: "1A3A5C", type: ShadingType.CLEAR }, margins: { top: 90, bottom: 90, left: 100, right: 100 },
      children: [new Paragraph({ children: [new TextRun({ text: t, bold: true, size: 20, color: "FFFFFF", font: "Arial" })] })] })) });
}
function tblR(cells, ws, fill = "FFFFFF") {
  return new TableRow({ children: cells.map((t, i) =>
    new TableCell({ borders: B, width: { size: ws[i], type: WidthType.DXA },
      shading: { fill, type: ShadingType.CLEAR }, margins: { top: 70, bottom: 70, left: 100, right: 100 },
      children: [new Paragraph({ children: [new TextRun({ text: t, size: 20, font: "Arial" })] })] })) });
}

const doc = new Document({
  numbering: {
    config: [
      { reference: "bullets", levels: [
        { level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
        { level: 1, format: LevelFormat.BULLET, text: "◦", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1080, hanging: 360 } } } }
      ]},
      { reference: "numbers", levels: [
        { level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
        { level: 1, format: LevelFormat.DECIMAL, text: "%2.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1080, hanging: 360 } } } }
      ]}
    ]
  },
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 32, bold: true, font: "Arial", color: "1A3A5C" },
        paragraph: { spacing: { before: 400, after: 200 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, font: "Arial", color: "1A3A5C" },
        paragraph: { spacing: { before: 300, after: 160 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 22, bold: true, font: "Arial", color: "2E6DA4" },
        paragraph: { spacing: { before: 220, after: 120 }, outlineLevel: 2 } },
    ]
  },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
    children: [

      // PORTADA
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 1440, after: 200 },
        children: [new TextRun({ text: "SYNAPSE COUNCIL v2.0", bold: true, size: 56, color: "1A3A5C", font: "Arial" })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 80, after: 80 },
        children: [new TextRun({ text: "PLAN DE MEJORA E INTEGRACIÓN", size: 34, color: "2E6DA4", font: "Arial", bold: true })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 80, after: 600 },
        children: [new TextRun({ text: "Informe Técnico Completo — Versión 1.0 | Abril 2026 | Óscar Fernández", size: 22, color: "666666", font: "Arial", italics: true })] }),
      new Table({ width: { size: CW, type: WidthType.DXA }, columnWidths: [CW],
        rows: [new TableRow({ children: [new TableCell({ borders: HB, width: { size: CW, type: WidthType.DXA },
          shading: { fill: "1A3A5C", type: ShadingType.CLEAR }, margins: { top: 200, bottom: 200, left: 280, right: 280 },
          children: [
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "RESUMEN EJECUTIVO", bold: true, size: 24, color: "FFFFFF", font: "Arial" })] }),
            new Paragraph({ spacing: { before: 120 }, children: [new TextRun({ text: "Este documento contiene el plan técnico completo para integrar las capacidades del Tribunal de Magistrados, el Evaluador de Convergencia, el Sistema de Reputación EMA, la Taxonomía de Intervenciones de CORAL v5.3, el QualityMonitor y la Memoria Híbrida en el pipeline secuencial de SynapseIA. Incluye el código exacto de cada cambio, los comandos de verificación, los tiempos estimados y un prompt listo para usar con un agente de desarrollo. Cubre tres horizontes temporales: correcciones inmediatas (hoy), mejoras de alto impacto (esta semana) y enriquecimiento del sistema (semana siguiente).", size: 20, color: "CCCCCC", font: "Arial" })] }),
          ]
        })] })] }),
      pb(),

      // ÍNDICE
      h1("ÍNDICE"),
      para("1.  Estado Actual del Sistema"),
      para("2.  Bugs Críticos — Corrección Inmediata (HOY)"),
      para("    2.1  Encoding corrupto en tribunal.py — _has_blocking_objection"),
      para("    2.2  Estimación de tokens incorrecta en agent_orchestrator.py"),
      para("    2.3  Modo hardcodeado en _sync_to_supabase"),
      para("3.  Mejoras de Alto Impacto — Esta Semana"),
      para("    3.1  Tribunal de Magistrados en el pipeline secuencial"),
      para("    3.2  ConvergenceEvaluator con parada anticipada"),
      para("    3.3  Informe final estructurado en JSON"),
      para("    3.4  Endpoint de diagnóstico del sistema"),
      para("4.  Mejoras de Enriquecimiento — Semana Siguiente"),
      para("    4.1  Taxonomía de intervenciones (de CORAL v5.3)"),
      para("    4.2  QualityMonitor de respuestas"),
      para("    4.3  Sistema de Reputación EMA operativo"),
      para("    4.4  Memoria híbrida SQLite + Supabase"),
      para("5.  Preparación para Cloud — Fase Posterior"),
      para("6.  Prompt Completo para Agente de Desarrollo"),
      para("7.  Orden de Implementación, Tiempos y Checklist Final"),
      pb(),

      // 1. ESTADO ACTUAL
      h1("1. ESTADO ACTUAL DEL SISTEMA"),
      para("Tras la sesión de depuración del 25 de abril de 2026, SynapseIA tiene dos subsistemas funcionando en paralelo que no están conectados entre sí. Comprender esta dualidad es esencial antes de implementar cualquier mejora."),
      sep(),
      h2("1.1  Sistema A — RoundController + AgentOrchestrator"),
      para("Arquitectura paralela completa con 4 fases (análisis, crítica, síntesis, tribunal), Protocolo de Consenso Forzado, WebSocket streaming, reputación EMA y frontend React. Todo esto existe en el código pero tenía el bug del circuit breaker que causaba fallos en cascada."),
      note("⚠️  ESTADO: Funcionalidad completa implementada pero frágil. El circuit breaker tenía un bug de inicialización. Los regex del tribunal tienen encoding corrupto. No se toca en este plan.", "FFE8E8"),
      h2("1.2  Sistema B — SequentialDebateController"),
      para("Pipeline lineal construido para aislar el bug del circuit breaker. Más simple pero robusto. Resultado verificado: 4 modelos (Meta, Mistral, Alibaba, DeepSeek) en 203 segundos con contexto acumulado y Wake & Sleep. Sin tribunal, sin convergencia, sin reputación."),
      note("✅  ESTADO: Funcionando en producción. Esta es la base sobre la que se construirán todas las mejoras de este plan.", "E8FFE8"),
      h2("1.3  Mapa de capacidades"),
      new Table({ width: { size: CW, type: WidthType.DXA }, columnWidths: [2600, 3380, 3380],
        rows: [
          tblH(["Capacidad", "Sistema A", "Sistema B (base)"], [2600, 3380, 3380]),
          tblR(["Modelos locales + Wake & Sleep", "✅", "✅"], [2600, 3380, 3380]),
          tblR(["Contexto acumulado entre turnos", "✅", "✅"], [2600, 3380, 3380], "F8F8F8"),
          tblR(["Fallback local si cloud falla", "❌", "✅"], [2600, 3380, 3380]),
          tblR(["Tribunal PCO (3 magistrados)", "✅ (encoding roto)", "❌ → integrar paso 2"], [2600, 3380, 3380], "F8F8F8"),
          tblR(["ConvergenceEvaluator", "✅", "❌ → integrar paso 3"], [2600, 3380, 3380]),
          tblR(["Informe JSON estructurado", "❌", "❌ → crear paso 4"], [2600, 3380, 3380], "F8F8F8"),
          tblR(["Taxonomía de intervenciones", "❌", "❌ → crear paso 5"], [2600, 3380, 3380]),
          tblR(["QualityMonitor", "❌", "❌ → crear paso 6"], [2600, 3380, 3380], "F8F8F8"),
          tblR(["Reputación EMA", "Config existe, sin código", "❌ → crear paso 7"], [2600, 3380, 3380]),
          tblR(["Memoria híbrida offline", "❌", "❌ → crear paso 8"], [2600, 3380, 3380], "F8F8F8"),
        ]
      }),
      pb(),

      // 2. BUGS CRÍTICOS
      h1("2. BUGS CRÍTICOS — CORRECCIÓN INMEDIATA (HOY)"),
      para("Estos tres bugs deben corregirse antes de implementar cualquier mejora. Son silenciosos — no producen errores visibles — pero rompen funcionalidades ya implementadas."),
      sep(),

      h2("2.1  Encoding corrupto en tribunal.py"),
      tag("IMPACTO: CRÍTICO — El PCO completo está roto silenciosamente"),
      para("El método _has_blocking_objection() en backend/engine/tribunal.py contiene caracteres UTF-8 corruptos en los patrones regex. Esto hace que el tribunal NUNCA detecte objeciones de bloqueo. El PCO siempre termina en la primera iteración independientemente de si los magistrados discrepen. Este bug invalida por completo el Protocolo de Consenso Forzado."),
      h3("Archivo: backend/engine/tribunal.py"),
      tag("BUSCAR Y REEMPLAZAR — _has_blocking_objection():"),
      ...codes([
        "# ACTUAL (ROTO — caracteres corruptos visibles como ÃN, Ã):",
        'r"##\\s*ObjeciÃ³n de Bloqueo:\\s*SÃ"  ← CORRUPTO',
        'r"Bloqueo:\\s*SÃ"                      ← CORRUPTO',
        "",
        "# CORRECTO:",
        'blocking_patterns = [',
        '    r"##\\s*Objeción de Bloqueo:\\s*Sí",',
        '    r"##\\s*Objeción de Bloqueo:\\s*SI",',
        '    r"##\\s*Objecion de Bloqueo:\\s*Si",   # sin tilde fallback',
        '    r"Objeción de Bloqueo:\\s*S[íi]",',
        '    r"Objecion de Bloqueo:\\s*Si",',
        '    r"Bloqueo:\\s*S[íi]",',
        '    r"Blocking Objection:\\s*Yes",          # modelos en inglés',
        '    r"BLOCK:\\s*YES",',
        ']',
      ]),
      tag("TAMBIÉN CORREGIR en _extract_score() y _extract_dissent_areas():"),
      ...codes([
        '# _extract_score() — patrones corruptos a corregir:',
        '"PuntuaciÃ³n TÃ©cnica"   →   "Puntuación Técnica"',
        '"PuntuaciÃ³n de Riesgo"  →   "Puntuación de Riesgo"',
        '',
        '# _extract_dissent_areas() — secciones corruptas a corregir:',
        '"Argumentos Rechazados"  →  verificar si tiene corrupción',
        '"Riesgos CrÃ­ticos"      →  "Riesgos Críticos"',
        '"Ãreas de Incertidumbre" →  "Áreas de Incertidumbre"',
      ]),
      tag("VERIFICACIÓN:", "27AE60"),
      ...codes([
        'python -c "',
        'from backend.engine.tribunal import TribunalMagistratus',
        't = TribunalMagistratus.__new__(TribunalMagistratus)',
        'assert t._has_blocking_objection("## Objeción de Bloqueo: Sí") == True',
        'assert t._has_blocking_objection("## Objecion de Bloqueo: Si") == True',
        'assert t._has_blocking_objection("sin objeción alguna") == False',
        'print("PASS: encoding corrected")',
        '"',
      ]),

      h2("2.2  Estimación de tokens incorrecta en agent_orchestrator.py"),
      tag("IMPACTO: MEDIO — Métricas de Supabase y sistema de reputación imprecisos"),
      para("La estimación usa división por 4 (ratio inglés). El español tiene palabras más largas, el ratio correcto es ~3.3 caracteres por token. Esto afecta las métricas persistidas en Supabase y los scores del sistema de reputación EMA."),
      h3("Archivo: backend/engine/agent_orchestrator.py"),
      ...codes([
        "# ACTUAL (impreciso para español):",
        "tokens_in = len(system_prompt) // 4 + len(user_prompt) // 4",
        "tokens_out = len(response_text) // 4",
        "",
        "# CORRECTO:",
        "tokens_in = (len(system_prompt) + len(user_prompt)) // 3",
        "tokens_out = len(response_text) // 3",
      ]),

      h2("2.3  Modo hardcodeado en _sync_to_supabase"),
      tag("IMPACTO: BAJO — Trazabilidad incorrecta en Supabase"),
      para("El método siempre envía mode: 'local_only' independientemente del modo real. Esto hace que en Supabase todos los debates aparezcan como 'local_only' aunque hayan usado otros modos."),
      h3("Archivo: backend/engine/sequential_debate_controller.py"),
      ...codes([
        "# ACTUAL:",
        'async def _sync_to_supabase(self, session, session_id: str):',
        '    debate_data = { "mode": "local_only",  # HARDCODEADO',
        "",
        "# CORRECTO:",
        'async def _sync_to_supabase(self, session, session_id: str, mode: str = "local_only"):',
        '    debate_data = { "mode": mode,  # dinámico',
        "",
        "# Y en create_debate(), cambiar la llamada a:",
        'asyncio.create_task(self._sync_to_supabase(session, session_id, mode))',
      ]),
      pb(),

      // 3. ALTO IMPACTO
      h1("3. MEJORAS DE ALTO IMPACTO — ESTA SEMANA"),

      h2("3.1  Tribunal de Magistrados en el pipeline secuencial"),
      tag("IMPACTO: MUY ALTO — Transforma el debate de 4 modelos en deliberación con veredicto soberano"),
      para("El TribunalMagistratus ya existe y funciona (una vez corregido el encoding). El _generate_verdict() actual es solo texto plano. La integración añade una fase final al pipeline que ejecuta los 3 magistrados con sus roles (Evidencias, Riesgos, Alineación) sobre la síntesis de todos los turnos."),
      h3("Paso A — Ampliar DebateSession con nuevos campos"),
      ...codes([
        "@dataclass",
        "class DebateSession:",
        "    id: str",
        "    topic: str",
        "    turns: List[DebateTurn] = field(default_factory=list)",
        "    context_history: List[Dict[str, Any]] = field(default_factory=list)",
        "    status: str = 'created'",
        "    created_at: datetime = field(default_factory=datetime.now)",
        "    completed_at: Optional[datetime] = None",
        "    final_verdict: Optional[str] = None",
        "    # NUEVOS CAMPOS:",
        "    tribunal_verdict: Optional[Dict[str, Any]] = None",
        "    consensus_score: float = 0.0",
        "    convergence_level: str = 'UNKNOWN'",
        "    structured_report: Optional[Dict[str, Any]] = None",
      ]),
      h3("Paso B — Método _run_tribunal() en SequentialDebateController"),
      ...codes([
        "async def _run_tribunal(self, session: DebateSession, topic: str, db_session) -> Optional[Dict]:",
        "    completed = [t for t in session.turns if t.status.startswith('completed')]",
        "    if len(completed) < 2:",
        "        logger.warning('tribunal.skipped_not_enough_turns', turns=len(completed))",
        "        return None",
        "",
        "    # Construir síntesis de todos los turnos completados",
        "    parts = []",
        "    for t in completed:",
        "        parts.append(",
        "            f'=== {t.agent.name} ({t.agent.role.value}) ===\\n'",
        "            f'Modelo: {t.agent.model} | Empresa: {t.agent.provider}\\n\\n'",
        "            f'{t.response_received}'",
        "        )",
        "    local_synthesis = '\\n\\n'.join(parts)",
        "",
        "    try:",
        "        from backend.engine.tribunal import TribunalMagistratus",
        "        from backend.engine.agent_orchestrator import AgentOrchestrator",
        "        tribunal = TribunalMagistratus(orchestrator=AgentOrchestrator())",
        "        verdict = await tribunal.deliberate(",
        "            query=topic,",
        "            local_synthesis=local_synthesis,",
        "            cloud_synthesis='',  # vacío en modo local_only",
        "            db_session=db_session,",
        "            session_id=session.id,",
        "        )",
        "        logger.info('tribunal.completed', session_id=session.id,",
        "                    consensus=verdict.consensus_reached,",
        "                    iterations=verdict.iterations_required)",
        "        return {",
        "            'verdict_text': verdict.verdict_text,",
        "            'consensus_reached': verdict.consensus_reached,",
        "            'iterations_required': verdict.iterations_required,",
        "            'evidence_score': verdict.evidence_score,",
        "            'risk_score': verdict.risk_score,",
        "            'alignment_score': verdict.alignment_score,",
        "            'dissent_areas': verdict.dissent_areas,",
        "        }",
        "    except Exception as e:",
        "        logger.error('tribunal.failed', session_id=session.id, error=str(e))",
        "        return None  # NUNCA propagar — el debate ya completó sus turnos",
      ]),
      h3("Paso C — Llamar al tribunal en create_debate() antes de _generate_verdict"),
      ...codes([
        "# En create_debate(), justo antes de session.final_verdict = self._generate_verdict(session):",
        "",
        "tribunal_result = None",
        "completed_count = len([t for t in session.turns if t.status.startswith('completed')])",
        "if completed_count >= 2:",
        "    logger.info('sequential_debate.running_tribunal', session_id=session_id)",
        "    async with AsyncSessionLocal() as db_t:",
        "        tribunal_result = await self._run_tribunal(session, topic, db_t)",
        "",
        "if tribunal_result:",
        "    session.final_verdict = tribunal_result['verdict_text']",
        "    session.tribunal_verdict = tribunal_result",
        "    logger.info('sequential_debate.tribunal_verdict_set', session_id=session_id)",
        "else:",
        "    session.final_verdict = self._generate_verdict(session)  # fallback",
      ]),
      note("VERIFICACIÓN: Tras implementar, lanzar un debate y buscar en logs: 'tribunal.deliberating', 'tribunal.magistrate_opinion' (x3 mínimo), 'tribunal.completed'. El campo final_verdict debe contener '## Veredicto Final', '## Fundamentos', '## Pasos Accionables'.", "E8F4F8"),

      h2("3.2  ConvergenceEvaluator con parada anticipada"),
      tag("IMPACTO: ALTO — Ahorra hasta 140 segundos y 700 tokens cuando hay consenso temprano"),
      para("El ConvergenceEvaluator calcula un composite_score ponderado: similitud semántica (40%) + acuerdo en puntos clave (30%) + estabilidad entre rondas (30%). Si supera 0.75 recomienda detener. Si hay alta estabilidad (>0.85) con consenso parcial también detiene."),
      h3("Modificación en create_debate() — añadir tras cada 2 turnos:"),
      ...codes([
        "from backend.engine.convergence import ConvergenceEvaluator",
        "# Añadir al __init__:",
        "self.convergence_evaluator = ConvergenceEvaluator()",
        "",
        "# En create_debate(), antes del bucle:",
        "previous_syntheses = []",
        "",
        "# DENTRO DEL BUCLE, después de session.turns.append(turn):",
        "if idx >= 2 and idx % 2 == 0:  # cada par de turnos",
        "    last_two = [t.response_received for t in session.turns[-2:]",
        "                if t.status.startswith('completed') and t.response_received]",
        "    if len(last_two) == 2:",
        "        conv = self.convergence_evaluator.evaluate(",
        "            local_synthesis=last_two[0],",
        "            cloud_synthesis=last_two[1],",
        "            round_number=idx // 2,",
        "            max_rounds=len(agents_config) // 2,",
        "            previous_syntheses=previous_syntheses,",
        "        )",
        "        session.consensus_score = conv.similarity_score",
        "        session.convergence_level = conv.consensus_level",
        "        previous_syntheses.append((last_two[0], last_two[1]))",
        "        logger.info('sequential_debate.convergence', session_id=session_id,",
        "                    turn=idx, level=conv.consensus_level,",
        "                    score=round(conv.similarity_score, 3), stop=conv.should_stop)",
        "        if conv.should_stop and idx < len(agents_config):",
        "            logger.info('sequential_debate.early_stop', session_id=session_id,",
        "                        turns_done=idx, turns_total=len(agents_config))",
        "            break",
      ]),

      h2("3.3  Informe final estructurado en JSON"),
      tag("IMPACTO: ALTO — Output consumible por otros sistemas, exportable, navegable"),
      para("Actualmente el debate termina con texto plano en final_verdict. No hay estructura de datos. La integración añade _generate_structured_report() que usa mistral:7b con temperatura 0.2 para generar un JSON con consensos, discrepancias, argumentos, veredicto y métricas."),
      h3("Método _generate_structured_report() en SequentialDebateController:"),
      ...codes([
        "async def _generate_structured_report(self, session: DebateSession, topic: str) -> Dict:",
        "    completed = [t for t in session.turns if t.status.startswith('completed')]",
        "    context = '\\n\\n'.join([",
        "        f'[{t.agent.role.value.upper()} — {t.agent.name} ({t.agent.model})]:\\n{t.response_received}'",
        "        for t in completed",
        "    ])",
        "    if session.tribunal_verdict:",
        "        context += f'\\n\\n[VEREDICTO TRIBUNAL]:\\n{session.final_verdict}'",
        "",
        "    prompt = f'''Eres el generador de informes del Synapse Council.",
        "    Analiza el debate y genera ÚNICAMENTE JSON válido. Sin texto extra. Sin markdown.",
        "",
        "    DEBATE (session_id={session.id}, topic={topic}):",
        "    {context[:7000]}",
        "",
        "    JSON requerido:",
        "    {{",
        '        "debate_id": "{session.id}",',
        '        "topic": "{topic}",',
        '        "executive_summary": "150 palabras max",',
        '        "consensus_points": ["punto 1"],',
        '        "disagreement_points": ["punto 1"],',
        '        "strongest_arguments": [{{"argument":"","agent":"","model":""}}],',
        '        "weakest_arguments": [{{"argument":"","reason":""}}],',
        '        "open_questions": ["pregunta 1"],',
        '        "detected_biases": [],',
        '        "final_verdict": "100 palabras",',
        '        "debate_quality_score": 0.0,',
        '        "recommendation": "continuar/cerrar/reabrir",',
        '        "models_used": [],',
        '        "companies_represented": [],',
        '        "consensus_score": {session.consensus_score},',
        '        "convergence_level": "{session.convergence_level}"',
        "    }}",
        "    '''",
        "",
        "    try:",
        "        parts = []",
        "        async for token in self.local_manager.generate(",
        "            engine_type=EngineType('ollama'), model='mistral:7b',",
        "            prompt=prompt, system='Solo JSON válido. Sin markdown. Sin texto extra.',",
        "            temperature=0.2, max_tokens=1500, stream=True):",
        "            parts.append(token)",
        "        content = ''.join(parts).strip()",
        "        # Limpiar bloques ```json```",
        "        if '```' in content:",
        "            for part in content.split('```'):",
        "                p = part.strip()",
        "                if p.startswith('json'): p = p[4:].strip()",
        "                if p.startswith('{'): content = p; break",
        "        import json",
        "        report = json.loads(content)",
        "        report.update({'status':'completed',",
        "                       'total_tokens': sum(t.tokens_out for t in session.turns),",
        "                       'total_latency_ms': sum(t.latency_ms for t in session.turns)})",
        "        return report",
        "    except Exception as e:",
        "        logger.error('report_generator.failed', error=str(e))",
        "        return {'status':'completed_no_json','debate_id':session.id,'topic':topic,",
        "                'final_verdict':session.final_verdict or '',",
        "                'total_tokens':sum(t.tokens_out for t in session.turns),",
        "                'models_used':list(set(t.agent.model for t in session.turns))}",
      ]),
      para("Llamar a este método al final de create_debate() y persistir en SequentialDebate como campo JSON. Añadir endpoint GET /api/v1/debates/{session_id}/report."),

      h2("3.4  Endpoint de diagnóstico del sistema"),
      tag("IMPACTO: MEDIO — Elimina el debugging a ciegas del circuit breaker"),
      para("Añadir en backend/api/routes/debug.py (nuevo archivo):"),
      ...codes([
        "@router.get('/api/v1/debug/system')",
        "async def system_debug():",
        "    import time",
        "    from backend.engine.local_engine_manager import LocalEngineManager, EngineType",
        "    lm = LocalEngineManager()",
        "    return {",
        "        'circuit_breakers': {",
        "            e.value: {",
        "                'open': lm.circuit_broken_until[e] > time.time(),",
        "                'seconds_remaining': max(0, int(lm.circuit_broken_until[e] - time.time())),",
        "                'failure_count': lm.engine_failures[e],",
        "            }",
        "            for e in lm.circuit_broken_until",
        "        },",
        "        'engine_health': {k.value: v for k, v in lm.engine_health.items()},",
        "    }",
        "",
        "# Registrar en main.py:",
        "app.include_router(debug_router, prefix='')",
        "",
        "# Verificación:",
        "curl http://localhost:8000/api/v1/debug/system",
      ]),
      pb(),

      // 4. ENRIQUECIMIENTO
      h1("4. MEJORAS DE ENRIQUECIMIENTO — SEMANA SIGUIENTE"),

      h2("4.1  Taxonomía de intervenciones de CORAL v5.3"),
      tag("IMPACTO: MEDIO — Enriquece el análisis del debate con estructura discursiva"),
      para("CORAL v5.3 tiene un enum TipoIntervencion con valores: apertura, argumento, contraargumento, refutacion, pregunta, consenso, sintesis, critica, validacion. Permite analizar el tipo de acto discursivo de cada turno, no solo quién habló. El detector es heurístico basado en palabras clave en español."),
      h3("Nuevo archivo: backend/engine/intervention_taxonomy.py"),
      ...codes([
        "from enum import Enum",
        "from typing import List",
        "",
        "class TipoIntervencion(Enum):",
        "    APERTURA = 'apertura'",
        "    ARGUMENTO = 'argumento'",
        "    CONTRAARGUMENTO = 'contraargumento'",
        "    REFUTACION = 'refutacion'",
        "    PREGUNTA = 'pregunta'",
        "    CONSENSO = 'consenso'",
        "    SINTESIS = 'sintesis'",
        "    CRITICA = 'critica'",
        "    VALIDACION = 'validacion'",
        "    DESCONOCIDO = 'desconocido'",
        "",
        "class InterventionDetector:",
        "    REFUTACION_KW = ['sin embargo','contradice','incorrecto','error en',",
        "                     'no es cierto','refuto','contradigo','no coincide']",
        "    CONSENSO_KW   = ['coincido','de acuerdo','consenso','todos coinciden',",
        "                     'convergencia','coincidimos','comparto','acepto']",
        "    PREGUNTA_KW   = ['¿por qué','¿cómo','¿qué evidencia','me pregunto',",
        "                     'no queda claro','¿es posible']",
        "    CRITICA_KW    = ['debilidad','fallo','problema con','insuficiente',",
        "                     'no considera','omite','sesgado','cuestionable']",
        "",
        "    def detect(self, content: str, role: str) -> TipoIntervencion:",
        "        if not content: return TipoIntervencion.DESCONOCIDO",
        "        cl = content.lower()",
        "        # Refutación (más específico — prioridad 1)",
        "        if sum(1 for kw in self.REFUTACION_KW if kw in cl) >= 2:",
        "            return TipoIntervencion.REFUTACION",
        "        # Consenso",
        "        if sum(1 for kw in self.CONSENSO_KW if kw in cl) >= 2:",
        "            return TipoIntervencion.CONSENSO",
        "        # Pregunta",
        "        if any(kw in cl for kw in self.PREGUNTA_KW):",
        "            return TipoIntervencion.PREGUNTA",
        "        # Por rol",
        "        if role == 'critic':",
        "            return TipoIntervencion.REFUTACION if sum(1 for kw in self.CRITICA_KW if kw in cl) >= 1 else TipoIntervencion.CRITICA",
        "        if role == 'synthesizer': return TipoIntervencion.SINTESIS",
        "        if role in ('analyst', 'refiner'): return TipoIntervencion.ARGUMENTO",
        "        if role == 'moderator': return TipoIntervencion.VALIDACION",
        "        return TipoIntervencion.DESCONOCIDO",
        "",
        "    def build_summary(self, turns: list) -> dict:",
        "        counts = {t.value: 0 for t in TipoIntervencion}",
        "        for t in turns:",
        "            it = getattr(t, 'intervention_type', 'desconocido')",
        "            counts[it] = counts.get(it, 0) + 1",
        "        total = max(sum(counts.values()), 1)",
        "        return {'by_type': counts,",
        "                'consensus_ratio': counts.get('consenso',0)/total,",
        "                'conflict_ratio': (counts.get('refutacion',0)+counts.get('critica',0))/total}",
      ]),
      h3("Modificar DebateTurn y create_debate():"),
      ...codes([
        "# En DebateTurn dataclass añadir:",
        "intervention_type: str = 'desconocido'",
        "",
        "# En create_debate(), después de turn.status = 'completed':",
        "from backend.engine.intervention_taxonomy import InterventionDetector",
        "turn.intervention_type = InterventionDetector().detect(",
        "    turn.response_received, turn.agent.role.value).value",
        "",
        "# En DebateSession.build_context_prompt(), añadir tipo en cabecera:",
        "lines.append(f'### Turno {t.turn_number}: {t.agent.name} [{t.intervention_type}]')",
      ]),

      h2("4.2  QualityMonitor de respuestas"),
      tag("IMPACTO: MEDIO — Filtra respuestas truncadas del contexto del siguiente agente"),
      para("Los modelos locales pueden generar respuestas muy cortas (timeout, límite de tokens), sin el formato esperado, o truncadas a mitad de frase. Sin detección, estas respuestas se pasan al siguiente agente degradando todo el debate."),
      h3("Nuevo archivo: backend/engine/quality_monitor.py"),
      ...codes([
        "class QualityMonitor:",
        "    MIN_LENGTH = 80",
        "    EXPECTED = {",
        "        'analyst':     ['análisis','posición','argumento'],",
        "        'critic':      ['validaci','crítica','veredicto'],",
        "        'synthesizer': ['síntesis','convergencia','consenso'],",
        "        'refiner':     ['refinamiento','argumento'],",
        "        'moderator':   ['veredicto','fundamento'],",
        "    }",
        "    def evaluate(self, content: str, role: str) -> tuple:",
        "        if not content: return 0.0, ['Respuesta vacía']",
        "        issues, score = [], 1.0",
        "        if len(content) < self.MIN_LENGTH:",
        "            issues.append(f'Muy corta: {len(content)} chars'); score -= 0.5",
        "        missing = [s for s in self.EXPECTED.get(role,[]) if s not in content.lower()]",
        "        if missing: issues.append(f'Sin secciones: {missing}'); score -= 0.15*len(missing)",
        "        if content.strip() and content.strip()[-1] not in '.!?}]\"':",
        "            issues.append('Posiblemente truncada'); score -= 0.1",
        "        return max(0.0, score), issues",
        "    def is_usable(self, content: str, role: str) -> bool:",
        "        score, _ = self.evaluate(content, role)",
        "        return score >= 0.4",
        "    def summary(self, turns: list) -> dict:",
        "        scores = [self.evaluate(t.response_received, t.agent.role.value)[0]",
        "                  for t in turns if t.response_received and t.status.startswith('completed')]",
        "        return {'avg': round(sum(scores)/len(scores),3) if scores else 0.0,",
        "                'min': round(min(scores),3) if scores else 0.0,",
        "                'low_quality': sum(1 for s in scores if s < 0.4)}",
      ]),
      h3("Integración en build_context_prompt():"),
      ...codes([
        "qm = QualityMonitor()",
        "for turn in self.turns:",
        "    if turn.status == 'completed':",
        "        if qm.is_usable(turn.response_received, turn.agent.role.value):",
        "            lines.append(f'### Turno {turn.turn_number}: {turn.agent.name}')",
        "            lines.append(turn.response_received)",
        "        else:",
        "            lines.append(f'### Turno {turn.turn_number}: {turn.agent.name} [OMITIDO — baja calidad]')",
      ]),

      h2("4.3  Sistema de Reputación EMA operativo"),
      tag("IMPACTO: ALTO A LARGO PLAZO — El sistema aprende qué modelos funcionan mejor por rol"),
      para("Config.py ya tiene REPUTATION_EMA_ALPHA=0.3 y REPUTATION_MIN_DEBATES_FOR_WEIGHT=3. Pero no hay código que los use. La implementación requiere una tabla en BD, un manager y actualización tras cada turno."),
      h3("Modelo en backend/database/models.py:"),
      ...codes([
        "class ModelReputation(Base):",
        "    __tablename__ = 'model_reputation'",
        "    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)",
        "    model: Mapped[str] = mapped_column(String(100), nullable=False)",
        "    provider: Mapped[str] = mapped_column(String(50), nullable=False)",
        "    role: Mapped[str] = mapped_column(String(30), nullable=False)",
        "    tsa_score: Mapped[float] = mapped_column(Float, default=0.5)   # Supervivencia Argumentos",
        "    iid_score: Mapped[float] = mapped_column(Float, default=0.5)   # Independencia Dialéctica",
        "    pvt_score: Mapped[float] = mapped_column(Float, default=0.5)   # Precisión Técnica",
        "    efficiency_score: Mapped[float] = mapped_column(Float, default=0.5)",
        "    reputation_score: Mapped[float] = mapped_column(Float, default=0.5)  # compuesto",
        "    total_debates: Mapped[int] = mapped_column(Integer, default=0)",
        "    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)",
        "    __table_args__ = (UniqueConstraint('model','role',name='uq_model_role'),)",
      ]),
      h3("Nuevo archivo: backend/engine/reputation_manager.py"),
      ...codes([
        "class ReputationManager:",
        "    ALPHA = 0.3  # EMA alpha: últimos ~3 debates pesan 65% del score",
        "",
        "    async def update_after_turn(self, model, provider, role,",
        "                                tokens_out, latency_ms, success, intervention_type):",
        "        if not settings.AGENT_REPUTATION_ENABLED: return",
        "        try:",
        "            efficiency = min((tokens_out / max(latency_ms,1)) * 1000 / 10.0, 1.0)",
        "            tsa_new = 1.0 if intervention_type not in ['refutacion'] else 0.3",
        "            iid_new = 1.0 if intervention_type in ['argumento','refutacion','critica'] else 0.5",
        "            pvt_new = 1.0 if success else 0.0",
        "            async with AsyncSessionLocal() as db:",
        "                result = await db.execute(select(ModelReputation)",
        "                    .where(ModelReputation.model==model, ModelReputation.role==role))",
        "                rep = result.scalar_one_or_none()",
        "                if rep is None:",
        "                    rep = ModelReputation(model=model, provider=provider, role=role)",
        "                    db.add(rep)",
        "                a = self.ALPHA",
        "                rep.tsa_score = a*tsa_new + (1-a)*rep.tsa_score",
        "                rep.iid_score = a*iid_new + (1-a)*rep.iid_score",
        "                rep.pvt_score = a*pvt_new + (1-a)*rep.pvt_score",
        "                rep.efficiency_score = a*efficiency + (1-a)*rep.efficiency_score",
        "                rep.reputation_score = (rep.tsa_score*0.3 + rep.iid_score*0.2 +",
        "                                        rep.pvt_score*0.3 + rep.efficiency_score*0.2)",
        "                rep.total_debates += 1",
        "                rep.updated_at = datetime.utcnow()",
        "                await db.commit()",
        "        except Exception as e:",
        "            logger.error('reputation.update_failed', model=model, error=str(e))",
        "",
        "    async def get_best_for_role(self, role: str, candidates: list) -> Optional[str]:",
        "        if not settings.AGENT_REPUTATION_ENABLED: return None",
        "        async with AsyncSessionLocal() as db:",
        "            result = await db.execute(select(ModelReputation)",
        "                .where(ModelReputation.role==role,",
        "                       ModelReputation.model.in_(candidates),",
        "                       ModelReputation.total_debates>=settings.REPUTATION_MIN_DEBATES_FOR_WEIGHT)",
        "                .order_by(ModelReputation.reputation_score.desc()).limit(1))",
        "            best = result.scalar_one_or_none()",
        "            return best.model if best else None",
      ]),
      h3("Integración en create_debate():"),
      ...codes([
        "# Después de session.turns.append(turn), si el turno completó:",
        "if turn.status.startswith('completed'):",
        "    rep_manager = ReputationManager()",
        "    asyncio.create_task(rep_manager.update_after_turn(",
        "        model=turn.agent.model, provider=turn.agent.provider,",
        "        role=turn.agent.role.value, tokens_out=turn.tokens_out,",
        "        latency_ms=turn.latency_ms, success=True,",
        "        intervention_type=getattr(turn,'intervention_type','desconocido'),",
        "    ))",
      ]),

      h2("4.4  Memoria híbrida SQLite + Supabase"),
      tag("IMPACTO: ALTO — Elimina dependencia de red para el flujo del debate"),
      para("Patrón tomado de CORAL v5.3: SQLite local siempre disponible y garantizado. Supabase en background como backup asíncrono. Si Supabase tiene latencia o está caído, el debate continúa sin interrupciones. La sincronización se encola y se procesa cuando hay conexión."),
      h3("Nuevo archivo: backend/memory/hybrid_memory.py"),
      ...codes([
        "class HybridMemory:",
        "    def __init__(self):",
        "        self.supabase = get_supabase_service()",
        "        self._queue = asyncio.Queue()",
        "        self._task = None",
        "",
        "    async def start(self):",
        "        self._task = asyncio.create_task(self._worker())",
        "",
        "    async def stop(self):",
        "        if self._task:",
        "            await self._queue.join()",
        "            self._task.cancel()",
        "",
        "    async def enqueue_sync(self, session, session_id: str, mode: str):",
        "        '''Llama esto en lugar de _sync_to_supabase directamente.'''",
        "        data = self._build(session, session_id, mode)",
        "        await self._queue.put(('debate', data))",
        "",
        "    async def _worker(self):",
        "        while True:",
        "            try:",
        "                kind, data = await asyncio.wait_for(self._queue.get(), timeout=30.0)",
        "                try:",
        "                    if kind == 'debate':",
        "                        await self.supabase.sync_debate(data)",
        "                        logger.info('hybrid_memory.synced', session_id=data.get('id'))",
        "                except Exception as e:",
        "                    logger.warning('hybrid_memory.supabase_failed', error=str(e))",
        "                    # Silencioso — no bloquea nada",
        "                finally:",
        "                    self._queue.task_done()",
        "            except asyncio.TimeoutError: continue",
        "            except asyncio.CancelledError: break",
        "",
        "    def _build(self, session, session_id, mode) -> dict:",
        "        return {'id': session_id, 'topic': session.topic, 'mode': mode,",
        "                'status': session.status, 'final_verdict': session.final_verdict,",
        "                'total_tokens_out': sum(t.tokens_out for t in session.turns),",
        "                'turns': [{",
        "                    'id': f'{session_id}_turn_{t.turn_number}',",
        "                    'debate_id': session_id, 'turn_number': t.turn_number,",
        "                    'agent_name': t.agent.name, 'model': t.agent.model,",
        "                    'intervention_type': getattr(t,'intervention_type','desconocido'),",
        "                    'response_received': t.response_received[:15000],",
        "                    'tokens_out': t.tokens_out, 'latency_ms': t.latency_ms,",
        "                } for t in session.turns]}",
      ]),
      h3("Integración en main.py:"),
      ...codes([
        "from backend.memory.hybrid_memory import HybridMemory",
        "hybrid_memory = HybridMemory()",
        "",
        "@asynccontextmanager",
        "async def lifespan(app: FastAPI):",
        "    await init_db()",
        "    await node_discoverer.start()",
        "    await hybrid_memory.start()   # NUEVO",
        "    yield",
        "    await hybrid_memory.stop()    # NUEVO",
        "    await node_discoverer.stop()",
        "",
        "# En SequentialDebateController: reemplazar asyncio.create_task(_sync_to_supabase())",
        "# por: asyncio.create_task(hybrid_memory.enqueue_sync(session, session_id, mode))",
      ]),
      pb(),

      // 5. CLOUD
      h1("5. PREPARACIÓN PARA CLOUD — FASE POSTERIOR"),
      para("Todos los cambios de las secciones 3 y 4 deben implementarse teniendo en mente que en una fase posterior se añadirán agentes cloud. El diseño correcto permite activarlos con un cambio de configuración, sin modificar el pipeline."),
      h2("5.1  Principio de cloud-readiness"),
      para("El SequentialDebateController ya soporta node='CLOUD' y engine='openrouter'. Lo que se debe preparar ahora es: (1) un AgentRegistry con cloud disabled, (2) variables de entorno listas, (3) la lógica de selección de agentes preparada para consultar reputación por modelo Y por tipo (local/cloud)."),
      h2("5.2  Variables de entorno a añadir en .env.example ahora"),
      ...codes([
        "# Cloud — vacíos en fase 1, activar añadiendo la key en fase 2",
        "GOOGLE_AI_API_KEY=",
        "GROQ_API_KEY=",
        "# OPENROUTER_API_KEY ya existe",
        "",
        "# Control de activación",
        "CLOUD_AGENTS_ENABLED=false",
        "CLOUD_TIMEOUT_SECONDS=30",
        "CLOUD_MAX_RETRIES=2",
        "",
        "# Modelos cloud que se activarán en fase 2:",
        "# analyst_gemini:    gemini-1.5-flash     (Google AI Studio, gratuito 50 RPD)",
        "# critic_groq:       llama-3.1-8b-instant (Groq, gratuito 30 RPM)",
        "# synthesizer_or:    deepseek-r1:free      (OpenRouter, limitado)",
      ]),
      pb(),

      // 6. PROMPT COMPLETO
      h1("6. PROMPT COMPLETO PARA AGENTE DE DESARROLLO"),
      para("El siguiente prompt está diseñado para usarse directamente con Claude Code. Contiene todo el contexto necesario para implementar las 9 mejoras sin leer este informe. Copiar y pegar tal cual."),
      sep(),
      new Table({ width: { size: CW, type: WidthType.DXA }, columnWidths: [CW],
        rows: [new TableRow({ children: [new TableCell({ borders: HB, width: { size: CW, type: WidthType.DXA },
          shading: { fill: "0D1117", type: ShadingType.CLEAR }, margins: { top: 200, bottom: 200, left: 240, right: 240 },
          children: [
            new Paragraph({ children: [new TextRun({ text: "══ INICIO DEL PROMPT ══", bold: true, size: 22, color: "00FF41", font: "Courier New" })] }),
            new Paragraph({ spacing: {before:120}, children: [new TextRun({ text: "Eres un ingeniero senior de Python. Tienes acceso completo al proyecto SynapseIA. Tu tarea es implementar 9 mejoras en orden estricto. Después de CADA PASO debes ejecutar la verificación indicada y confirmar PASS antes de continuar con el siguiente.", size: 20, color: "E0E0E0", font: "Courier New" })] }),
            new Paragraph({ spacing: {before:120}, children: [new TextRun({ text: "ESTADO DEL PROYECTO:", bold: true, size: 20, color: "FFD700", font: "Courier New" })] }),
            new Paragraph({ children: [new TextRun({ text: "Master: 192.168.1.41:8000 (FastAPI). Worker: 192.168.1.43:11434 (Ollama).", size: 20, color: "E0E0E0", font: "Courier New" })] }),
            new Paragraph({ children: [new TextRun({ text: "Modelos OK: llama3:8b, mistral:7b, qwen2.5:3b, deepseek-r1:7b, llama3.1:8b, tinyllama.", size: 20, color: "E0E0E0", font: "Courier New" })] }),
            new Paragraph({ children: [new TextRun({ text: "SequentialDebateController: FUNCIONA. RoundController/AgentOrchestrator: NO TOCAR.", size: 20, color: "E0E0E0", font: "Courier New" })] }),
            new Paragraph({ spacing: {before:120}, children: [new TextRun({ text: "RESTRICCIONES ABSOLUTAS:", bold: true, size: 20, color: "FF6B6B", font: "Courier New" })] }),
            new Paragraph({ children: [new TextRun({ text: "1) NO modificar round_controller.py ni agent_orchestrator.py (solo leerlos)", size: 20, color: "FF9999", font: "Courier New" })] }),
            new Paragraph({ children: [new TextRun({ text: "2) NO añadir dependencias cloud de pago en esta fase", size: 20, color: "FF9999", font: "Courier New" })] }),
            new Paragraph({ children: [new TextRun({ text: "3) Todo async — ninguna llamada bloqueante en el event loop", size: 20, color: "FF9999", font: "Courier New" })] }),
            new Paragraph({ children: [new TextRun({ text: "4) Cada mejora captura sus excepciones internamente — nunca propagar al pipeline", size: 20, color: "FF9999", font: "Courier New" })] }),
          ]
        })] })] }),
      para(" "),
      ...codes([
        "━━━ PASO 1 — BUGS CRÍTICOS (HOY) ━━━",
        "",
        "1A: tribunal.py — _has_blocking_objection()",
        "Lee el archivo. Busca caracteres corruptos (ÃN, Ã, secuencias UTF-8 rotas).",
        "Corrígelos en: blocking_patterns, _extract_score(), _extract_dissent_areas().",
        "Los patrones correctos son: 'Objeción de Bloqueo: Sí', 'Objecion de Bloqueo: Si',",
        "'Bloqueo: S[íi]', 'Blocking Objection: Yes', 'Puntuación Técnica', 'Riesgos Críticos'.",
        "TEST: python -c \"from backend.engine.tribunal import TribunalMagistratus; t=TribunalMagistratus.__new__(TribunalMagistratus); assert t._has_blocking_objection('## Objeción de Bloqueo: Sí')==True; print('PASS')\"",
        "",
        "1B: agent_orchestrator.py — tokens",
        "Cambia: tokens_in = len(sp)//4 + len(up)//4  →  (len(sp)+len(up))//3",
        "Cambia: tokens_out = len(rt)//4  →  len(rt)//3",
        "TEST: python -c \"from backend.engine.agent_orchestrator import AgentOrchestrator; print('PASS')\"",
        "",
        "1C: sequential_debate_controller.py — _sync_to_supabase",
        "Cambia firma: async def _sync_to_supabase(self, session, session_id, mode='local_only')",
        "Cambia 'mode': 'local_only' por 'mode': mode en el dict.",
        "Actualiza la llamada asyncio.create_task(...) para pasar el modo.",
      ]),
      para(" "),
      ...codes([
        "━━━ PASO 2 — TRIBUNAL EN PIPELINE SECUENCIAL ━━━",
        "",
        "2A: Añadir a DebateSession: tribunal_verdict=None, consensus_score=0.0, convergence_level='UNKNOWN', structured_report=None",
        "",
        "2B: Implementar _run_tribunal(self, session, topic, db_session):",
        "  - Filtrar turnos con status.startswith('completed'). Si <2: log warning, return None.",
        "  - Concatenar: '=== {agent.name} ({role}) ===\\n{response}' para cada turno.",
        "  - Importar TribunalMagistratus y AgentOrchestrator.",
        "  - Llamar tribunal.deliberate(query=topic, local_synthesis=..., cloud_synthesis='', db_session=db_session, session_id=session.id)",
        "  - Retornar dict con verdict_text, consensus_reached, iterations_required, evidence_score, risk_score, alignment_score, dissent_areas.",
        "  - En except Exception: logger.error(...); return None",
        "",
        "2C: En create_debate(), antes de _generate_verdict():",
        "  - Si completed_count >= 2: llamar _run_tribunal() con AsyncSessionLocal",
        "  - Si retorna resultado: session.final_verdict = resultado['verdict_text'], session.tribunal_verdict = resultado",
        "  - Si retorna None: session.final_verdict = self._generate_verdict(session)",
        "",
        "TEST: curl -X POST http://localhost:8000/api/v1/debates/sequential \\",
        "  -H 'Content-Type: application/json' \\",
        "  -d '{\"topic\": \"Test tribunal: 2+2=4\", \"mode\": \"local_only\"}'",
        "# Verificar en logs: tribunal.deliberating y tribunal.completed",
        "# Verificar en respuesta: final_verdict contiene '## Veredicto Final'",
      ]),
      para(" "),
      ...codes([
        "━━━ PASO 3 — CONVERGENCE EVALUATOR ━━━",
        "",
        "Añadir al __init__: self.convergence_evaluator = ConvergenceEvaluator()",
        "Añadir antes del bucle: previous_syntheses = []",
        "",
        "Dentro del bucle, después de session.turns.append(turn):",
        "  if idx >= 2 and idx % 2 == 0:",
        "    last_two = [t.response_received for t in session.turns[-2:] if t.status.startswith('completed')]",
        "    if len(last_two) == 2:",
        "      conv = self.convergence_evaluator.evaluate(last_two[0], last_two[1], idx//2, len(agents_config)//2, previous_syntheses)",
        "      session.consensus_score = conv.similarity_score",
        "      session.convergence_level = conv.consensus_level",
        "      previous_syntheses.append((last_two[0], last_two[1]))",
        "      logger.info('convergence', level=conv.consensus_level, score=round(conv.similarity_score,3))",
        "      if conv.should_stop and idx < len(agents_config): break",
        "",
        "TEST: lanzar debate y verificar log 'sequential_debate.convergence' con score y level.",
      ]),
      para(" "),
      ...codes([
        "━━━ PASO 4 — INFORME JSON ESTRUCTURADO ━━━",
        "",
        "Implementar _generate_structured_report(self, session, topic) -> dict:",
        "  - Construir contexto de turnos completados con cabeceras",
        "  - Si hay tribunal_verdict, añadir al contexto",
        "  - Prompt: instrucción de generar SOLO JSON con campos definidos en informe",
        "  - Llamar local_manager.generate() con mistral:7b, temperature=0.2, max_tokens=1500",
        "  - Limpiar bloques ```json``` con split('```')",
        "  - json.loads() — si falla: retornar dict básico con final_verdict como texto",
        "  - Añadir status, total_tokens, total_latency_ms al resultado",
        "",
        "Llamar al final de create_debate() y asignar a session.structured_report",
        "Persistir en SequentialDebate como campo JSON en la BD",
        "Añadir endpoint: GET /api/v1/debates/{session_id}/report",
        "",
        "TEST: curl http://localhost:8000/api/v1/debates/{SESSION_ID}/report",
        "# Debe retornar JSON con: executive_summary, consensus_points, final_verdict",
      ]),
      para(" "),
      ...codes([
        "━━━ PASO 5 — ENDPOINT DE DIAGNÓSTICO ━━━",
        "",
        "Crear backend/api/routes/debug.py con router = APIRouter()",
        "@router.get('/api/v1/debug/system')",
        "async def debug(): return circuit breakers, engine health, engine failures",
        "",
        "Registrar en main.py: app.include_router(debug_router)",
        "",
        "TEST: curl http://localhost:8000/api/v1/debug/system",
        "# Debe mostrar state de todos los circuit breakers con open/seconds_remaining",
      ]),
      para(" "),
      ...codes([
        "━━━ PASO 6 — TAXONOMÍA DE INTERVENCIONES ━━━",
        "",
        "Crear backend/engine/intervention_taxonomy.py con TipoIntervencion (enum) e InterventionDetector.",
        "El detector usa listas de palabras clave en español para identificar el tipo.",
        "Prioridad: refutacion > consenso > pregunta > por_rol.",
        "",
        "Añadir a DebateTurn: intervention_type: str = 'desconocido'",
        "En create_debate() after turn.status='completed': detectar y asignar tipo.",
        "En build_context_prompt(): incluir [tipo] en la cabecera de cada turno.",
        "",
        "TEST: python -c \"from backend.engine.intervention_taxonomy import InterventionDetector,TipoIntervencion; d=InterventionDetector(); assert d.detect('sin embargo contradice lo dicho','critic')==TipoIntervencion.REFUTACION; print('PASS')\"",
      ]),
      para(" "),
      ...codes([
        "━━━ PASO 7 — QUALITY MONITOR ━━━",
        "",
        "Crear backend/engine/quality_monitor.py con QualityMonitor.",
        "evaluate() retorna (score 0-1, lista de issues). Chequea: longitud mínima 80 chars,",
        "secciones esperadas por rol, si parece truncada.",
        "is_usable() retorna True si score >= 0.4.",
        "",
        "En build_context_prompt(): filtrar turnos con is_usable() == False,",
        "marcándolos como [OMITIDO] en el historial.",
        "",
        "En _generate_structured_report(): añadir quality_metrics al JSON del informe.",
        "",
        "TEST: python -c \"from backend.engine.quality_monitor import QualityMonitor; qm=QualityMonitor(); s,_=qm.evaluate('x','analyst'); assert s<0.5; print('PASS')\"",
      ]),
      para(" "),
      ...codes([
        "━━━ PASO 8 — REPUTACIÓN EMA ━━━",
        "",
        "Añadir ModelReputation a backend/database/models.py con campos:",
        "model, provider, role, tsa_score, iid_score, pvt_score, efficiency_score,",
        "reputation_score (todos Float default 0.5), total_debates (Int default 0).",
        "UniqueConstraint en (model, role).",
        "",
        "Ejecutar migración: python -c \"from backend.database.local_db import init_db; import asyncio; asyncio.run(init_db())\"",
        "",
        "Crear backend/engine/reputation_manager.py con ReputationManager.",
        "update_after_turn(): calcula TSA, IID, PVT, efficiency. Aplica EMA alpha=0.3. Siempre en try/except.",
        "get_best_for_role(): consulta BD, retorna model con mejor score >= MIN_DEBATES umbral.",
        "",
        "En create_debate(): después de cada turno completado:",
        "asyncio.create_task(rep_manager.update_after_turn(...))",
        "",
        "Añadir endpoint GET /api/v1/reputation que retorne todas las reputaciones.",
        "",
        "TEST después de 3 debates: curl http://localhost:8000/api/v1/reputation",
        "# Debe mostrar scores EMA por modelo y rol",
      ]),
      para(" "),
      ...codes([
        "━━━ PASO 9 — MEMORIA HÍBRIDA ━━━",
        "",
        "Crear backend/memory/__init__.py (vacío)",
        "Crear backend/memory/hybrid_memory.py con HybridMemory.",
        "start()/stop(): gestiona asyncio.Task del worker.",
        "enqueue_sync(): encola datos para Supabase. Nunca lanza excepción al caller.",
        "_worker(): procesa cola. En except de supabase: log warning y continúa silenciosamente.",
        "",
        "En main.py lifespan: await hybrid_memory.start() / await hybrid_memory.stop()",
        "En SequentialDebateController: reemplazar asyncio.create_task(_sync_to_supabase())",
        "por asyncio.create_task(hybrid_memory.enqueue_sync(session, session_id, mode))",
        "",
        "TEST: Cambiar SUPABASE_URL a URL inválida en .env. Lanzar debate.",
        "# Debe completarse sin errores. Solo warning en logs: 'hybrid_memory.supabase_failed'",
        "# Restaurar URL. Reiniciar. El worker procesará la cola pendiente.",
        "",
        "══ FIN DEL PROMPT ══",
      ]),
      pb(),

      // 7. ORDEN Y CHECKLIST
      h1("7. ORDEN DE IMPLEMENTACIÓN, TIEMPOS Y CHECKLIST FINAL"),
      new Table({ width: { size: CW, type: WidthType.DXA }, columnWidths: [420, 3000, 1100, 1100, 1100, 1440, 2200],
        rows: [
          tblH(["#", "Mejora", "Impacto", "Riesgo", "Tiempo", "Cuándo", "Archivo(s)"], [420, 3000, 1100, 1100, 1100, 1440, 2200]),
          tblR(["1A", "Fix encoding tribunal.py", "CRÍTICO", "Nulo", "15 min", "HOY", "tribunal.py"], [420, 3000, 1100, 1100, 1100, 1440, 2200], "FFF0F0"),
          tblR(["1B", "Fix tokens orchestrator", "Medio", "Nulo", "5 min", "HOY", "agent_orchestrator.py"], [420, 3000, 1100, 1100, 1100, 1440, 2200]),
          tblR(["1C", "Fix modo sync", "Bajo", "Nulo", "5 min", "HOY", "sequential_debate_controller.py"], [420, 3000, 1100, 1100, 1100, 1440, 2200], "F8F8F8"),
          tblR(["2", "Tribunal en secuencial", "Muy Alto", "Bajo", "3-4 h", "Semana 1", "sequential_debate_controller.py"], [420, 3000, 1100, 1100, 1100, 1440, 2200]),
          tblR(["3", "ConvergenceEvaluator", "Alto", "Bajo", "1-2 h", "Semana 1", "sequential_debate_controller.py"], [420, 3000, 1100, 1100, 1100, 1440, 2200], "F8F8F8"),
          tblR(["4", "Informe JSON", "Alto", "Bajo", "2 h", "Semana 1", "sequential_debate_controller.py + routes/debate.py"], [420, 3000, 1100, 1100, 1100, 1440, 2200]),
          tblR(["5", "Endpoint diagnóstico", "Medio", "Nulo", "30 min", "Semana 1", "routes/debug.py (nuevo)"], [420, 3000, 1100, 1100, 1100, 1440, 2200], "F8F8F8"),
          tblR(["6", "Taxonomía intervenciones", "Medio", "Nulo", "1 h", "Semana 2", "intervention_taxonomy.py (nuevo)"], [420, 3000, 1100, 1100, 1100, 1440, 2200]),
          tblR(["7", "QualityMonitor", "Medio", "Bajo", "1.5 h", "Semana 2", "quality_monitor.py (nuevo)"], [420, 3000, 1100, 1100, 1100, 1440, 2200], "F8F8F8"),
          tblR(["8", "Reputación EMA", "Alto LP", "Medio", "4 h", "Semana 2", "reputation_manager.py (nuevo) + models.py"], [420, 3000, 1100, 1100, 1100, 1440, 2200]),
          tblR(["9", "Memoria híbrida", "Alto", "Bajo", "2 h", "Semana 2", "memory/hybrid_memory.py (nuevo) + main.py"], [420, 3000, 1100, 1100, 1100, 1440, 2200], "F8F8F8"),
        ]
      }),
      para(" "),
      h2("7.1  Checklist de verificación final — ejecutar cuando todo esté implementado"),
      num("El sistema arranca sin errores: curl http://localhost:8000/health → status: ok"),
      num("Circuit breakers visibles: curl http://localhost:8000/api/v1/debug/system"),
      num("Debate corto (2 agentes) completa: lanzar y verificar logs convergence_check"),
      num("Tribunal ejecuta: logs muestran tribunal.deliberating + tribunal.completed"),
      num("Informe JSON generado: curl .../debates/{ID}/report → JSON con consensus_points"),
      num("Taxonomía funciona: logs muestran intervention_type para cada turno"),
      num("QualityMonitor activo: logs muestran cuando omite turno de baja calidad"),
      num("Reputación se actualiza: tras 3 debates, curl .../reputation muestra scores EMA"),
      num("Offline funciona: desactivar Supabase, lanzar debate, debe completar sin errores"),
      num("Debate completo de referencia: 4 agentes, topic complejo, verificar informe final"),
      sep(),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 300 },
        children: [new TextRun({ text: "Synapse Council v2.0 — Plan de Mejora v1.0 — Óscar Fernández — Abril 2026", size: 18, color: "999999", font: "Arial", italics: true })] }),
    ]
  }]
});

const outputPath = process.argv[2] || "c:\\Users\\usuario\\Desktop\\Synapse_Master\\SynapseIA_Plan_Mejora_Completo.docx";

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync(outputPath, buffer);
  console.log("✅ Documento generado:", outputPath);
}).catch(err => { console.error(err); process.exit(1); });
